# These are supported funding model platforms
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# This is a YAML file
# https://yaml.org/

# github: [nhquydev]
ko_fi: nhquydev
# https://thanks.dev/profiles/nhquydev
thanks_dev: u/gh/nhquydev
